### ISSUE TITLE
Unexpected ES6 feature 'let'

### ISSUE THREAD

**Issue by NorthLake** [FreezeLogic/jsLint2-for-Brackets#1]
You say it fully supports ES6, but when I try to use let it gives the error "Unexpected ES6 feature 'let'.   let x = 2;"
This is literally the only code in the entire document:
`let x = 2;`

**Comment by pmw57** [comment]
The older version of JSLint that is used here needs a JSLint directive to be set, to indicate ES6 support.

    /*jslint es6 */

More recent versions of JSLint don't require that directive to support ES6.
